name: Generate and Deploy Redirects

on:
  push:
    branches: [ second ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate redirects file
        run: |
          # Aqui você colocaria o script para gerar o arquivo _redirects
          # Por exemplo, usando um template e dados de um arquivo JSON
          echo "/old-page http://new-domain.com/new-page 301" > _redirects
      - name: Commit changes
        run: git add _redirects
